### ISSUE TITLE
配置起来有点困难…

### ISSUE THREAD

**Issue by zhangyu921** [acyortjs/acyort#43]
没搞定，circleci出错了好多……
最后按着示例博客里的配置…… 并且把几条删除文件夹的命令，因为文件夹不存在报错了，移除掉才勉强跑通，最后也没build出index.html

所以public里面到底装了啥…… 示例博客忽略了没上传

地址： https://github.com/zhangyu921/blog-acyort

**Comment by LoeiFy** [comment]
第 19 行 `- run: git clone https://github.com/acyortjs/theme-donob.git`
应该为 `- run: git clone https://github.com/acyortjs/theme-donob.git themes/donob`

第 24 行 ` # - run: cp -R public/* . ` 不要注释这行

你直接用这个配置 https://github.com/LoeiFy/Recordum/blob/master/.circleci/config.yml
把对应用户名换掉就行了

**Comment by zhangyu921** [comment]
@LoeiFy 这块有点问题
![image](https://user-images.githubusercontent.com/19166761/41075530-95d1b248-6a3f-11e8-9d05-7b60d2f3cb95.png)

**Comment by zhangyu921** [comment]
是不是可以不用Git仓库的切换来做，直接Build一个站点在另一个目录里，然后把gh-pages分支完全覆盖掉？

**Comment by LoeiFy** [comment]
```yml
# config.yml
# 只显示重要设置项

user:  # 你的 GitHub username
repository:  # 你的 GitHub repository

public_dir: public # 重要，跟 CircleCi 配置相同: public
timezone:  # 设置你的时区
token:  # 你的`read-token`
```

看清楚这里重要的设置点

你的 `public_dir` 设置错误了，还有记得把 gh-pages 分支清空或者只留下 .gitignore CNAME 两个文件
